[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
settlr = "DdKS6wL5UKk8EAnTVfGUBThcDuqAy79ZyChr5S9eXJjC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
